enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"

[Reddit]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
arch = "arm64-v8a"

[YouTube-Music]
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "arm64-v8a"

[Google-Photos]
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
arch = "arm64-v8a"

[Instagram]
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram"
arch = "arm64-v8a"
version = "401.0.0.48.79"
included-patches = "'Limit feed to followed profiles' 'Anonymous story viewing' 'Hide explore feed' 'Hide navigation buttons' 'Hide suggested content' 'Open links externally' 'Disable story auto flipping'"

[TikTok]
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok"
arch = "arm64-v8a"

[Messenger]
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger"
arch = "arm64-v8a"

[Proton-Mail]
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
arch = "arm64-v8a"

[Proton-VPN]
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
arch = "arm64-v8a"

[SoundCloud]
uptodown-dlurl = "http://soundcloud.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud"
arch = "arm64-v8a"
